export const GET_POST_DETAIL_REQUEST = "GET_POST_DETAIL_REQUEST";
export const GET_POST_DETAIL_SUCCESS = "GET_POST_DETAIL_SUCCESS";
export const GET_POST_DETAIL_FAILED = "GET_POST_DETAIL_FAILED";
export const GET_LIST_POST_REQUEST = "GET_LIST_POST_REQUEST";
export const GET_LIST_POST_SUCCESS = "GET_LIST_POST_SUCCESS";
export const GET_LIST_POST_FAILED = "GET_LIST_POST_FAILED";