export const GET_COLOR_REQUEST = "GET_COLOR_REQUEST";
export const GET_COLOR_SUCCESS  = "GET_COLOR_SUCCESS";
export const GET_COLOR_FAILED = "GET_COLOR_FAILED";
export const PUT_COLOR_REQUEST = "PUT_COLOR_REQUEST";
export const PUT_COLOR_SUCCESS = "PUT_COLOR_SUCCESS";
export const PUT_COLOR_FAILED = "PUT_COLOR_FAILED";

