export const GET_PRODUCT_IN_PAYMENT_REQUEST = "GET_PRODUCT_IN_PAYMENT_REQUEST";
export const GET_PRODUCT_IN_PAYMENT_SUCCESS = "GET_PRODUCT_IN_PAYMENT_SUCCESS";
export const GET_PRODUCT_IN_PAYMENT_FAILED = "GET_PRODUCT_IN_PRODUCT_FAILED";
export const DELETE_PRODUCT_IN_PAYMENT_REQUEST = "DELETE_PRODUCT_IN_PAYMENT_REQUEST";
export const DELETE_PRODUCT_IN_PAYMENT_SUCCESS = "DELETE_PRODUCT_IN_PAYMENT_SUCCESS";
export const DELETE_PRODUCT_IN_PAYMENT_FAILED = "DELETE_PRODUCT_IN_PAYMENT_FAILED";
