export const GET_LIST_POST_REQUEST = "GET_LIST_POST_REQUEST";
export const GET_LIST_POST_SUCCESS = "GET_LIST_POST_SUCCESS";
export const GET_LIST_POST_FAILED = "GET_LIST_POST_FAILED";

export const GET_POST_ID_REQUEST = "GET_POST_ID_REQUEST";
export const GET_POST_ID_SUCCESS = "GET_POST_ID_SUCCESS";
export const GET_POST_ID_FAILED = "GET_POST_ID_FAILED";
