export const GET_LIST_PRODUCT_REQUEST = "GET_LIST_PRODUCT_REQUEST";
export const GET_LIST_PRODUCT_SUCCESS = "GET_LIST_PRODUCT_SUCCESS";
export const GET_LIST_PRODUCT_FAILED = "GET_LIST_PRODUCT_FAILED";
export const GET_LIST_PRODUCT_CART_REQUEST = "GET_LIST_PRODUCT_CART_REQUEST";
export const GET_LIST_PRODUCT_CART_SUCCESS = "GET_LIST_PRODUCT_CART_SUCCESS";
export const GET_LIST_PRODUCT_CART_FAILED = "GET_LIST_PRODUCT_CART_FAILED";